---
- name: Create user for Gitea.
  user:
    comment: Gitea
    name: "{{ gitea_user }}"
    home: "{{ gitea_user_home }}"

- name: Create Gitea root and log folder.
  file:
    path: "{{ gitea_user_home }}/gitea/log"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_user }}"
    mode: 0755
    recurse: yes

- name: Check if Gitea is already installed.
  stat: path=/usr/local/bin/gitea
  register: gitea_bin

- name: Check gitea version
  shell: /usr/local/bin/gitea --version|cut -d ' ' -f 3
  check_mode: no
  changed_when: false
  register: gitea_bin_version
  when: gitea_bin.stat.islnk is defined


- name: Download Gitea.
  get_url:
    url: "{{ gitea_binary_url }}"
    dest: "{{ gitea_user_home }}/gitea/gitea"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_user }}"
    mode: 0755
    checksum: "sha256: {{ lookup('url', gitea_binary_sig_url).split(' ')[0] }}"
  when: gitea_bin.stat.islnk is not defined or
        gitea_bin_version != gitea_version

- include: init-setup.yml
- include: gitea-mysql.yml
  when: gitea_use_mysql

- name: Ensure Gitea is running.
  service: name=gitea state=started enabled=yes
